name: Terraform Destroy

on:
  workflow_dispatch:  # Manually triggered via GitHub UI

jobs:
  terraform-destroy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.9.5

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Terraform Init
      run: terraform init

    # Add an optional prompt or check before running destroy (to prevent accidents)
    - name: Confirm Terraform Destroy
      if: github.event.inputs.confirm_destroy == 'yes'
      run: echo "Confirmed"

    - name: Terraform Destroy
      run: terraform destroy -auto-approve
      env:
        TF_VAR_SELFSIGNED_CERT: ${{ secrets.TF_SELFSIGNED_CERT }}
        TF_VAR_SELFSIGNED_KEY: ${{ secrets.TF_SELFSIGNED_KEY }}
        TF_VAR_RDS_PASSWORD: ${{ secrets.RDS_PASSWORD }}
